name: my-ci

# on déclenche le workflow sur tout push
on: [push]
jobs:
    build-deploy-docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: ls
            - uses: docker/login-action@v3
              with:
                username: mon0ur
                password: Nour@2002
            - uses: docker/build-push-action@v5
              with:
                push: true
                tags: mon0ur/getting-started:latest
             
