name: my-ci

# on déclenche le workflow sur tout push
on: [push]
jobs:
    build-deploy-docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: ls
            - uses: docker/build-push-action@v5
              with:
                tags: mon0ur/gettin-started:latest
             
